### ISSUE TITLE
V1.0 Checklist

### ISSUE THREAD

**Issue by WilliamHayward** [WilliamHayward/LipwigCore#2]
Features to be implemented for version 1.0 of LipwigCore

* [x] Room create/Joining
* [x] Bi-directional message sending
* [x] Reconnection
* [x] Message queue for periods of disconnection
* [x] Closing rooms
* [x] Error Handling
* [x] Message verification (including origin of messages)
* [x] Reserved events
* [x] Kicking users

**Comment by WilliamHayward** [comment]
Any error should send an 'error' event message

**Comment by WilliamHayward** [comment]
All 1.0 features completed, updated on npm
