### ISSUE TITLE
V1.3 Checklist

### ISSUE THREAD

**Issue by WilliamHayward** [WilliamHayward/LipwigCore#7]
Features to be implemented for version 1.3 of LipwigCore

* [ ] Full suite of tests
* [ ] Full JSDoc comments
* [ ] Full public documentation
